development:
  adapter: postgresql
  host: localhost
  database: seladex_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  port: 5432
  encoding: Latin1


# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000


# test:
#   adapter: postgresql
#   encoding: unicode
#   database: seladex_test
#   pool: 5
#   username: vagrant
#   password: vagrant
#   port: 5432  
#   timeout: 5000

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: seladex_development
#   pool: 5
#   username: vagrant
#   password: vagrant
#   port: 5432  
#   timeout: 5000
